-- MySQL Script generated by MySQL Workbench
-- Tue Aug  7 17:47:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`USER` (
  `User_id` VARCHAR(15) NOT NULL,
  `User_password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_id_UNIQUE` (`User_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`STORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`STORY` (
  `Group_id` VARCHAR(15) NOT NULL,
  `Story_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Group_id`, `Story_id`),
  UNIQUE INDEX `Group_id_UNIQUE` (`Group_id` ASC) VISIBLE,
  UNIQUE INDEX `Story_id_UNIQUE` (`Story_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`GROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`GROUP` (
  `Group_id` VARCHAR(15) NOT NULL,
  `User_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Group_id`, `User_id`),
  INDEX `fk_User_has_table1_table11_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_User_has_table1_User_idx` (`Group_id` ASC) VISIBLE,
  UNIQUE INDEX `Group_id_UNIQUE` (`Group_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_table1_User`
    FOREIGN KEY (`Group_id`)
    REFERENCES `test`.`USER` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_table1_table11`
    FOREIGN KEY (`User_id`)
    REFERENCES `test`.`STORY` (`Group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
